[build]
  functions = "netlify/functions"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

  [plugins.inputs]
    included_dirs = ["node_modules/@prisma/client", "prisma"]

[functions]
  included_files = ["node_modules/@prisma/client/**", "prisma/**"]
